# Introduction to NumPy

NumPy (Numerical Python) is a powerful library in Python used for numerical computations. It provides support for arrays, matrices, and a collection of mathematical functions to operate on these data structures efficiently.

In this notebook, we'll cover some key concepts and functionalities of NumPy that are essential for data science.

## Key Points Covered:
1. **Basic Operations**: Mean, sum, max, and min.
2. **Reshape**: How to reshape arrays.
3. **2D Arrays**: Creation, accessing elements, and slicing.
4. **Array Operations**: Element-wise operations and broadcasting.
5. **Linear Algebra**: Dot product, eigenvalues, and eigenvectors.
6. **Random Numbers**: Generating random arrays.
7. **Array Creation**: Arrays of zeros, ones, and identity matrices.
8. **Array Properties**: Shape, dimensions, and data type.
9. **Flattening and Raveling**: Flattening arrays.
10. **Stacking and Concatenation**: Combining arrays.


In [1]:
import numpy as np

In [2]:
# NumPy array
array = np.array([1, 2, 3, 4, 5])

print("Array:", array)

Array: [1 2 3 4 5]


In [4]:
# basic Statistics
mean_value = np.mean(array)
sum_value = np.sum(array)
max_value = np.max(array)
min_value = np.min(array)

print("Mean:", mean_value)
print("Sum:", sum_value)
print("Max:", max_value)
print("Min:", min_value)


Mean: 3.0
Sum: 15
Max: 5
Min: 1


In [7]:
# reshape the array
#reshaping changes the structure of the array without altering its data. Here, a 1D array is reshaped into a 2D column vector.
reshaped_array = array.reshape((5, 1))
print("Reshaped Array:\n", reshaped_array)


Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [8]:
# create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# accessing elements
print("Element at (1, 2):", array_2d[1, 2])

# slicing
print("First row:", array_2d[0])
print("First column:", array_2d[:, 0])
print("Subarray:\n", array_2d[0:2, 1:3])


2D Array:
 [[1 2 3]
 [4 5 6]]
Element at (1, 2): 6
First row: [1 2 3]
First column: [1 4]
Subarray:
 [[2 3]
 [5 6]]


In [9]:
# element-wise operations
array_2 = np.array([6, 7, 8, 9, 10])
sum_arrays = array + array_2
print("Sum of Arrays:", sum_arrays)

product_arrays = array * array_2
print("Product of Arrays:", product_arrays)


Sum of Arrays: [ 7  9 11 13 15]
Product of Arrays: [ 6 14 24 36 50]


Broadcasting allows operations between arrays of different shapes, automatically expanding the smaller array to match the larger one.

In [10]:
# broadcasting
array_broadcasted = array + np.array([10])
print("Broadcasted Array:", array_broadcasted)


Broadcasted Array: [11 12 13 14 15]


In [14]:
# dot product
dot_product = np.dot(array_2d, array_2d.T)
print("Dot Product:\n", dot_product)


Dot Product:
 [[14 32]
 [32 77]]


In [22]:
# eigenvalues and eigenvectors
square_matrix = np.array([[1, 2],
                          [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(square_matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [16]:
# random Numbers
random_array = np.random.rand(3, 3)  # random array of shape (3, 3) with values between 0 and 1
print("Random Array:\n", random_array)


Random Array:
 [[0.61500437 0.29221769 0.76390692]
 [0.35028783 0.34384587 0.04808479]
 [0.11180452 0.90184044 0.52252257]]


In [17]:
# creating arrays
zeros_array = np.zeros((3, 3))  # array of zeros
ones_array = np.ones((2, 3))    # array of ones
identity_matrix = np.eye(3)     # identity matrix

print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)
print("Identity Matrix:\n", identity_matrix)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# array Properties
print("Array Shape:", array_2d.shape)
print("Array Dimensions:", array_2d.ndim)
print("Array Data Type:", array_2d.dtype)


Array Shape: (2, 3)
Array Dimensions: 2
Array Data Type: int32


In [20]:
# flattening and raveling
#flattening converts a multi-dimensional array into a 1D array.
flattened_array = array_2d.flatten()
print("Flattened Array:", flattened_array)


Flattened Array: [1 2 3 4 5 6]


In [21]:
# stacking arrays
stacked_v = np.vstack((array, array))
stacked_h = np.hstack((array, array))

print("Stacked Vertically:\n", stacked_v)
print("Stacked Horizontally:", stacked_h)

# concatenation
concatenated_array = np.concatenate((array, array_2), axis=0)
print("Concatenated Array:", concatenated_array)


Stacked Vertically:
 [[1 2 3 4 5]
 [1 2 3 4 5]]
Stacked Horizontally: [1 2 3 4 5 1 2 3 4 5]
Concatenated Array: [ 1  2  3  4  5  6  7  8  9 10]
